# Generated by Django 2.1.5 on 2019-01-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.MealCategory'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
