# Generated by Django 2.1.5 on 2019-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
