# Generated by Django 2.1.5 on 2019-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190126_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_purchase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tel_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
